package tryAndCatch;

public class TryCatchFinallyIntro {

	public static void main(String[] args)
	{
//	   Try Block:
//			It is used to declare risky code only.
//			Controller visits inside the try block only once through out the life time
//			of the program.
//			Try block should be followed by either catch or finally
//			Multiple try blocks are not allowed.
//			
//		Catch Block:
//				It is used to handle the event generated from try block.
//				Catch block will get executed only if the event get generated in the
//				try block.
//				Catch block should be declared after try block.
//				Any number of catch blocks can be declared for single try block.
		
	//	finally:
		
	//	The finally block in Java is a block of code that is always executed, 
	//  regardless of whether an exception is thrown or not. This is useful for 
	//  ensuring that cleanup code is always executed, such as closing files or
	//  database connections.Finally block will get executed in all the circumstances.
	//	Finally block should be followed by catch block you can declare finally block 
	//  after try block, but it is not recommended.
		
//		throw:
//		The "throw" keyword is used to throw an exception.
		
//		throws:
//		The "throws" keyword is used to declare exceptions. It specifies that there
		//may occur an exception in the method. It doesn't throw an exception. 
		//It is always used with method signature.




	}

}
